frase = 'Curso em Vídeo Python'

# FATIAMENTO

print(frase) # FRASE INTEIRA
print(frase[9]) # APENAS UM CARACTERE INDICADO PELO INDICE 9
print(frase[9:13]) # PRINTA DO 9 ATE O 13 (13 NAO ENTRA)
print(frase[9:21]) # NAO E RECOMENDADO COLOCAR VALORES ACIMA DO MAX APESAR DE FUNCIONAR
print(frase[9:21:2]) # VAI DE 9 ATE 21-1 PULANDO DE 2 EM 2
print(frase[:5]) # NAO TEM INICIO ENTOA COMEÇA DO CARACTERE 0 ATE O 5-1
print(frase[15:]) # VAI DO CARACTERE 15 ATE O FINAL
print(frase[9::3]) # COMEÇA DO 9 VAI ATE O FINAL PULANDO DE 3 EM 3

print(len(frase)) # PRINTA O TAMANHO DA STRING
print(frase.count('o')) # PRINTA A QUANTIDADE DE UM DETERMINADO CARACTERE
print(frase.count('o', 0, 13)) # CONTA CARACTERES EM UM LIMITE
print(frase.find('deo')) # MOSTRA ONDE ELE ENCONTROU (RETORNA POSICAO INICIAL) # RETORNA -1 SE NAO FOR ENCONTRADO

'Curso' in frase # VERIFICA SE EXISTE TAMBEM

# TRANSFORMACAO

frase = frase.replace('Python', 'Android')
print(frase)

frase.upper()
frase.lower()
frase.capitalize() # JOGA TUDO PRA MINUSCULO E A PRIMEIRA PRA MAIUSCULA
frase.title() # VAI COLOCAR MAIUSCULA EM TODOS OS INICIOS DE PALAVRA E O RESTO MINUSCULO
frase.strip() # REMOVE TODOS OS ESPAÇOS INUTEIS NO INICIO E FINAL DA STRING
frase.rstrip() # REMOVE OS ESPAÇOS DO INICIO (RIGHT)
frase.lstrip() # REMOVE OS ESPAÇOS DO FINAL (LEFT)

# DIVISAO

frase.split() # CRIA UMA DIVISAO EM TODOS OS ESPAÇOS (DIVIDE A STRING EM VARIAS)

# JUNÇAO

'-'.join(frase) # JUNTA TODOS OS ELEMENTOS DIVIDIDOS NOVAMENTE COM O HIFEN NESSE CASSO

# PARA ESCREVER TEXTOS GRANDES UTILIZA TRES "

print('Oi')

print("""AQUI POSSO COLOCAR UM TEXT """)